### ISSUE TITLE
change how quotes are handled?

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/split-string#3]
Currently, quotes are handled using an array because usually, the start and end quotes are the same characters. I'd like to propose changing the handling to an object hash similar to how brackets are handled. This will allow handling crazy quotes like these: `“ ”`.

If this seems like a good way to go, I'll do an update. To say backwards compatible, we can still allow an array to be passed in and convert it into an object.

**Comment by jonschlinkert** [comment]
> If this seems like a good way to go, I'll do an update.

absolutely, good call! Thanks!

**Comment by jonschlinkert** [comment]
> To say backwards compatible, we can still allow an array to be passed in and convert it into an object.

Sounds good. How about if we do that and release a minor, then just change it to an object and publish a major so we can transition the new version with more performant code as time allows?
