### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by wschella** [jonschlinkert/split-string#6]
The docs say:
```js
// Brackets

Also respects brackets unless disabled:

split('a (b c d) e', ' ');
//=> ['a', '(b c d)', 'e']
```

and 

```js
split('a.b,c', {separator: ','});
//=> ['a.b', 'c']
 
// you can also pass the separator as a string as the last argument
split('a.b,c', ',');
//=> ['a.b', 'c']
```

Both of which don't seem to hold anymore. As brackets seem to be ignored, and the last argument does not change the separator.

**Comment by jonschlinkert** [comment]
Thanks, I missed that. The separator must be defined on the options.

**Comment by doowb** [comment]
The docs have been updated to show the separator needs to be on the options.
