### ISSUE TITLE
Not returning the number of expected parts

### ISSUE THREAD

**Issue by polkhovsky** [jonschlinkert/split-string#8]
`splitString('||||', {separator: '|' }).length`
4
Expecting: 5.

**Comment by jonschlinkert** [comment]
Does this happen only when every character is a separator with a length of greater than 1? Any more information?

**Comment by polkhovsky** [comment]
Hi. Thanks for looking into this. This is not the only case. I’m working on an app that parses medical data. One of the rows failed column count check because after the split I got 97 columns vs expected 98. The number of separators in the string was correct. I couldn’t figure out the reason. The case above was the first case I tested. It failed so I didn’t look into it any further.

Thanks!

**Comment by jonschlinkert** [comment]
I just published 6.0.0 with some changes noted in the readme and changelog. This should be resolved. 

Thanks for creating the issue.
